// Generated by gencpp from file ros_posenet/Pose.msg
// DO NOT EDIT!


#ifndef ROS_POSENET_MESSAGE_POSE_H
#define ROS_POSENET_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ros_posenet/Keypoint.h>

namespace ros_posenet
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : keypoints()  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : keypoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ros_posenet::Keypoint_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_posenet::Keypoint_<ContainerAllocator> >> _keypoints_type;
  _keypoints_type keypoints;





  typedef boost::shared_ptr< ::ros_posenet::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_posenet::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::ros_posenet::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::ros_posenet::Pose > PosePtr;
typedef boost::shared_ptr< ::ros_posenet::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_posenet::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_posenet::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_posenet::Pose_<ContainerAllocator1> & lhs, const ::ros_posenet::Pose_<ContainerAllocator2> & rhs)
{
  return lhs.keypoints == rhs.keypoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_posenet::Pose_<ContainerAllocator1> & lhs, const ::ros_posenet::Pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_posenet

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_posenet::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_posenet::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_posenet::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_posenet::Pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_posenet::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_posenet::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_posenet::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e476a684ef3c919da15f180dd754305";
  }

  static const char* value(const ::ros_posenet::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e476a684ef3c919ULL;
  static const uint64_t static_value2 = 0xda15f180dd754305ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_posenet::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_posenet/Pose";
  }

  static const char* value(const ::ros_posenet::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_posenet::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_posenet/Keypoint[] keypoints\n"
"================================================================================\n"
"MSG: ros_posenet/Keypoint\n"
"string part\n"
"float64 score\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Point image_position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::ros_posenet::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_posenet::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.keypoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_posenet::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_posenet::Pose_<ContainerAllocator>& v)
  {
    s << indent << "keypoints[]" << std::endl;
    for (size_t i = 0; i < v.keypoints.size(); ++i)
    {
      s << indent << "  keypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_posenet::Keypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.keypoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_POSENET_MESSAGE_POSE_H
